export enum Response {
	USER_CREATE_ERROR = 'Felhasználó létrehozása nem sikerült',
	FIND_USER_ERROR = 'Felhasználó nem található',
	USERNAME_TAKEN = 'A felhasználónév már foglalt',
	CASE_CREATE_ERROR = 'Az ügy létrehozása nem sikerült',
	CASES_META_FIND_ERROR = 'Az ügyeket nem sikerült megtalálni',
	USER_NOT_SUBSCRIBED = 'Ezzel az email címmel előfizető nem létezik',
	SUBSCRIBED_NOT_FOUND = 'Előfizetőt nem sikerült megtalálni az adatbázisban',
	SUBSCRIBED_CREATE_ERROR = 'Előfizetőt nem sikerült létrehozni',
	MUST_BE_EMAIL = 'Érvényes email címet adj meg',
	CASE_NO_RIGHTS = 'Nincs joga megtekinteni ezt az ügyet',
	CASE_NOT_FOUND = 'Az ügy nem található',
	CASE_UPDATE_ERROR = 'Az ügy módosítása sikertelen',
	AREA_NOT_FOUND = 'Terület ilyen helyrajzi számmal nem található',
	MUST_BE_STRING = 'Szöveges értéknek kell lennie',
	AREA_ALREADY_EXISTS = 'Már létezik terület ezen a helyrajzi számon',
	INVALID_QUOTA_SUM = 'A tulajdonosi hányadok összege több mint 100%',
	INVALID_MOTION_TYPE = 'Érvénytelen indítványtípus',
	INVALID_DATA_TYPE = 'Érvénytelen adattípus',
	DELETE_ERROR = 'Sikertelen törlés',
	DATABASE_ERROR = 'Adatbázis hiba',
	INVALID_DATA = 'Érvénytelen adat'
}
